import "./globals.css";
import { fontOne , fonTwo } from "./font"


// const customFont = Montserrat({
//   subsets: ["latin"],
//   weight: ["600"],
//   display: "swap"
// })

// const customFontone = Oswald({
//   subsets: ["latin"],
//   weight: ["600"],
//   display: "swap"
// })


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontOne.className}>
        {/* changed font family */}
        {children}
      </body>
    </html>
  );
}
