import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>

          <h1>Main Layout</h1>

          <Link href={"/admin"} className="border border-white p-1 rounded" >admin</Link>
          <Link href={"/dashboard"} className="border border-white p-1 rounded"> dashboard</Link>
          <Link href={"/inroot"} className="border border-white p-1 rounded"> Not Root</Link>

        </nav>
        {children}
      </body>
    </html>
  );
}
